import type { AgentStage, OperationScenario } from "../domain/model";

const PRIMARY_STAGE_SUMMARIES = {
  receiving: "Protocolo e documentos recebidos",
  geometry: "Geometria validada sem erro topológico",
  "territorial-analysis": "APP e divergência territorial identificadas",
  conformity: "Score 62 e análise aprofundada recomendados",
  routing: "Processo encaminhado à Câmara de Águas",
  opinion: "Minuta preparada com evidências rastreáveis",
} satisfies Readonly<Record<AgentStage, string>>;

const SCENARIO_CATALOG = [
  {
    id: "PROC-2026-0512",
    title: "Divergência imagem x declaração em APP",
    processType: "Loteamento industrial",
    applicant: "Empreendedor Simulado Alfa Ltda.",
    municipality: "Bebedouro, SP",
    sector: "Indústria e loteamento",
    center: [-48.50, -21.50],
    polygon: processRing(-48.50, -21.50, 0.03),
    mapZoom: 13,
    focusLayer: "app",
    focusLayerLabel: "APP hídrica simulada",
    evidence: [
      {
        kind: "attribute-divergence",
        id: "image-divergence",
        title: "Divergência de área",
        measure: "36%",
        detail: "Área de intervenção: 174,61 ha na imagem e 128,43 ha declarados; valores distintos da área total do polígono sintético",
        source: "CAR 2.0 e imagem de 28 ago",
        observedAt: "2026-08-28",
        provenance: "provided-data",
      },
      {
        kind: "spatial-overlap",
        id: "app-overlap",
        title: "Interseção com APP",
        measure: "aprox. 605 ha",
        detail: "Polígono sintético integralmente contido na APP hídrica simulada; área aproximada no mapa",
        source: "Hidrografia e APP 30 m simulada",
        observedAt: "2026-09-02",
        provenance: "synthetic-data",
      },
    ],
    conflict: {
      title: "Conflito detectado",
      summary: "Divergência cadastral com sobreposição em APP",
      detail: "A imagem indica área declarada 36% maior; o polígono exibido cobre aproximadamente 605 ha de APP simulada.",
    },
    recommendation: {
      score: 62,
      route: "Análise técnica com prioridade",
      chamber: "Câmara de Águas e Recursos Hídricos",
      dueAt: "2026-09-06T18:00:00.000Z",
      provenance: "simulated-result",
    },
    arrivalTick: 0,
    branches: [
      branch("BR-0512-APP", "ESP-05", "territorial-analysis", "blocking", 2, "Verificação especializada de APP", "Sobreposição com a APP simulada identificada no mapa."),
      branch("BR-0512-IMG", "ESP-09", "territorial-analysis", "parallel", 4, "Confronto com imagem recente", "Divergência de 36% confirmada."),
      branch("BR-0512-JUR", "ESP-13", "territorial-analysis", "consultative", 4, "Consulta de enquadramento ambiental", "Revisão humana recomendada pela combinação de evidências."),
      branch("BR-0512-NOT", "ESP-20", "territorial-analysis", "operational", 5, "Preparação de notificação", "Minuta de comunicação preparada para conferência."),
    ],
    stageSummaries: PRIMARY_STAGE_SUMMARIES,
  },
  {
    id: "PROC-2026-0513",
    title: "Sobreposição com UC de Proteção Integral",
    processType: "Ampliação de unidade agroindustrial",
    applicant: "Empreendedor Simulado Beta S.A.",
    municipality: "Assis, SP",
    sector: "Agroindústria",
    center: [-50.420267, -22.540365],
    polygon: processRing(-50.420267, -22.540365, 0.018),
    mapZoom: 14,
    focusLayer: "ucPi",
    focusLayerLabel: "Estação Ecológica de Assis",
    evidence: [{
      kind: "spatial-overlap",
      id: "uc-pi-overlap",
      title: "UC de Proteção Integral",
      measure: "aprox. 120 ha",
      detail: "Interseção não declarada com a Estação Ecológica de Assis",
      source: "UC estadual de Proteção Integral, camada fornecida",
      observedAt: "2026-08-31",
      provenance: "provided-data",
    }],
    conflict: {
      title: "Restrição territorial",
      summary: "Interseção com UC de Proteção Integral",
      detail: "O empreendimento intercepta uma feição da camada fornecida.",
    },
    recommendation: {
      score: 58,
      route: "Análise técnica aprofundada",
      chamber: "Câmara de Biodiversidade",
      dueAt: "2026-09-08T18:00:00.000Z",
      provenance: "simulated-result",
    },
    arrivalTick: 3,
    branches: [
      branch("BR-0513-UCPI", "ESP-06", "territorial-analysis", "blocking", 3, "Análise da UC de Proteção Integral", "Interseção com feição fornecida confirmada."),
      branch("BR-0513-JUR", "ESP-13", "territorial-analysis", "consultative", 4, "Consulta jurídica sobre restrição crítica", "Análise aprofundada mantida."),
      branch("BR-0513-FIS", "ESP-15", "territorial-analysis", "parallel", 4, "Preparação de fiscalização estadual", "Alerta de vistoria registrado na simulação."),
      branch("BR-0513-NOT", "ESP-20", "territorial-analysis", "operational", 5, "Comunicação da pendência", "Aviso de restrição preparado."),
    ],
    stageSummaries: stageSummaries("UC de Proteção Integral consultada", "Score 58 e restrição territorial", "Câmara de Biodiversidade"),
  },
  {
    id: "PROC-2026-0514",
    title: "Interferência em UC de Uso Sustentável",
    processType: "Empreendimento turístico",
    applicant: "Empreendedor Simulado Gama Ltda.",
    municipality: "Ibiúna, SP",
    sector: "Turismo",
    center: [-47.186920, -23.691915],
    polygon: processRing(-47.186920, -23.691915, 0.014),
    mapZoom: 14,
    focusLayer: "ucUs",
    focusLayerLabel: "APA Itupararanga",
    evidence: [{
      kind: "spatial-overlap",
      id: "uc-us-overlap",
      title: "UC de Uso Sustentável",
      measure: "aprox. 130 ha",
      detail: "Polígono sintético contido na APA Itupararanga; área aproximada no mapa",
      source: "UC estadual de Uso Sustentável, camada fornecida",
      observedAt: "2026-09-01",
      provenance: "provided-data",
    }],
    conflict: null,
    recommendation: {
      score: 31,
      route: "Revisão técnica orientada",
      chamber: "Câmara de Biodiversidade",
      dueAt: "2026-09-10T18:00:00.000Z",
      provenance: "simulated-result",
    },
    arrivalTick: 5,
    branches: [
      branch("BR-0514-UCUS", "ESP-07", "territorial-analysis", "blocking", 3, "Análise da APA", "Sobreposição com a APA identificada no mapa.", "Interseção com a APA Itupararanga"),
      branch("BR-0514-BIO", "ESP-11", "territorial-analysis", "consultative", 4, "Consulta de conectividade", "Condicionante de conectividade sugerida.", "Interseção com UC de Uso Sustentável pede consulta de conectividade"),
    ],
    stageSummaries: stageSummaries("APA Itupararanga consultada", "Score 31 e revisão orientada", "Câmara de Biodiversidade"),
  },
  {
    id: "PROC-2026-0515",
    title: "Sobreposição com Terra Indígena",
    processType: "Linha de transmissão",
    applicant: "Empreendedor Simulado Delta Energia",
    municipality: "Cananéia, SP",
    sector: "Energia",
    center: [-47.846209, -24.760562],
    polygon: processRing(-47.846209, -24.760562, 0.016),
    mapZoom: 14,
    focusLayer: "terrasIndigenas",
    focusLayerLabel: "TI Pindoty/Araçá-Mirim",
    evidence: [{
      kind: "spatial-overlap",
      id: "ti-overlap",
      title: "Terra Indígena",
      measure: "aprox. 168 ha",
      detail: "Interseção com a TI Pindoty/Araçá-Mirim",
      source: "Terras Indígenas, camada fornecida",
      observedAt: "2026-09-01",
      provenance: "provided-data",
    }],
    conflict: {
      title: "Restrição territorial",
      summary: "Interseção com Terra Indígena",
      detail: "A diretriz simulada exige análise técnica especializada.",
    },
    recommendation: {
      score: 71,
      route: "Análise técnica especializada",
      chamber: "Câmara de Avaliação Integrada",
      dueAt: "2026-09-07T18:00:00.000Z",
      provenance: "simulated-result",
    },
    arrivalTick: 7,
    branches: [
      branch("BR-0515-TI", "ESP-08", "territorial-analysis", "blocking", 4, "Verificação sobre Terra Indígena", "Sobreposição com a TI identificada no mapa."),
      branch("BR-0515-FED", "ESP-14", "territorial-analysis", "blocking", 5, "Articulação federal", "Consulta federal simulada registrada para revisão humana."),
      branch("BR-0515-JUR", "ESP-13", "territorial-analysis", "consultative", 4, "Consulta jurídica especializada", "Restrição crítica mantida no encaminhamento."),
      branch("BR-0515-NOT", "ESP-20", "territorial-analysis", "operational", 5, "Comunicação da revisão humana", "Aviso ao analista preparado."),
    ],
    stageSummaries: stageSummaries("Terra Indígena consultada", "Score 71 e restrição crítica", "Câmara de Avaliação Integrada"),
  },
  {
    id: "PROC-2026-0516",
    title: "Sem sobreposição territorial relevante",
    processType: "Regularização de galpão",
    applicant: "Empreendedor Simulado Épsilon S.A.",
    municipality: "Franca, SP",
    sector: "Serviços",
    center: [-47.20, -20.40],
    polygon: processRing(-47.20, -20.40, 0.012),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Sem restrição identificada",
    evidence: [attributeEvidence("clearance", "Bateria territorial", "0 conflito", "Nenhuma sobreposição nas camadas cartográficas exibidas", "APP, UCs e Terras Indígenas")],
    conflict: null,
    recommendation: {
      score: 12,
      route: "Triagem simples por checklist",
      chamber: "Câmara de Atividades Gerais",
      dueAt: "2026-09-12T18:00:00.000Z",
      provenance: "simulated-result",
    },
    arrivalTick: 9,
    branches: [],
    stageSummaries: stageSummaries("Bateria territorial sem conflito", "Score 12 e checklist recomendado", "Câmara de Atividades Gerais"),
  },
  {
    id: "PROC-2026-0517",
    title: "Documento ausente e divergência no CAR",
    processType: "Ampliação de unidade logística",
    applicant: "Empreendedor Simulado Zeta Logística",
    municipality: "Bauru, SP",
    sector: "Logística",
    center: [-49.071, -22.324],
    polygon: processRing(-49.071, -22.324, 0.016),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Cadastro e CAR simulados",
    evidence: [attributeEvidence("car-divergence", "Divergência cadastral", "2 registros", "CAR e protocolo apresentam titulares distintos", "Cadastro e CAR simulados")],
    conflict: conflict("Pendência administrativa", "Documento obrigatório ausente e vínculo cadastral divergente"),
    recommendation: recommendation(43, "Complementação administrativa", "Câmara de Atividades Gerais", "2026-09-09T18:00:00.000Z"),
    arrivalTick: 11,
    branches: [
      branch("BR-0517-CAD", "ESP-02", "geometry", "blocking", 3, "Conferência cadastral e CAR", "Divergência de titularidade confirmada."),
      branch("BR-0517-ADM", "ESP-17", "geometry", "consultative", 4, "Resolução administrativa", "Lista de documentos para regularização produzida."),
      branch("BR-0517-NOT", "ESP-20", "geometry", "parallel", 5, "Notificação de complemento", "Mensagem demonstrativa preparada para envio."),
    ],
    stageSummaries: stageSummaries("Cadastro e vínculos conferidos", "Score 43 e complementação necessária", "Câmara de Atividades Gerais"),
  },
  {
    id: "PROC-2026-0518",
    title: "Geometria inválida e projeção incorreta",
    processType: "Parcelamento de solo",
    applicant: "Empreendedor Simulado Eta Urbanismo",
    municipality: "São José do Rio Preto, SP",
    sector: "Urbanização",
    center: [-49.376, -20.812],
    polygon: processRing(-49.376, -20.812, 0.02),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Geometria recebida",
    evidence: [attributeEvidence("geometry-error", "Validação geométrica", "2 falhas", "Geometria recebida com auto-interseção e referência incompatível; o mapa exibe apenas uma geometria ilustrativa válida", "Protocolo sintético")],
    conflict: conflict("Geometria inconsistente", "O polígono exige correção antes dos cruzamentos territoriais"),
    recommendation: recommendation(39, "Correção e reentrada na triagem", "Câmara de Uso do Solo", "2026-09-10T18:00:00.000Z"),
    arrivalTick: 13,
    branches: [
      branch("BR-0518-GEO", "ESP-03", "geometry", "blocking", 4, "Correção de topologia e projeção", "Geometria corrigida para continuidade da simulação."),
      branch("BR-0518-ADM", "ESP-17", "geometry", "consultative", 3, "Registro de reentrada administrativa", "Reentrada vinculada ao protocolo original."),
    ],
    stageSummaries: stageSummaries("Geometria corrigida na simulação", "Score 39 após reentrada", "Câmara de Uso do Solo"),
  },
  {
    id: "PROC-2026-0519",
    title: "Incompatibilidade entre atividade e zoneamento",
    processType: "Planta de tratamento de superfícies",
    applicant: "Empreendedor Simulado Teta Industrial",
    municipality: "Campinas, SP",
    sector: "Indústria",
    center: [-47.061, -22.907],
    polygon: processRing(-47.061, -22.907, 0.014),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "ZEE e zoneamento sintéticos",
    evidence: [attributeEvidence("zee-conflict", "Compatibilidade locacional", "1 alerta", "Incompatibilidade informada pela simulação; camada de ZEE não exibida no mapa", "ZEE e zoneamento municipal sintéticos")],
    conflict: conflict("Conflito de zoneamento", "A atividade declarada exige avaliação municipal e condicionante"),
    recommendation: recommendation(55, "Análise integrada de uso do solo", "Câmara de Uso do Solo", "2026-09-08T18:00:00.000Z"),
    arrivalTick: 15,
    branches: [
      branch("BR-0519-ZEE", "ESP-10", "territorial-analysis", "blocking", 4, "Compatibilidade com ZEE", "Alerta documental encaminhado para conferência cartográfica."),
      branch("BR-0519-MUN", "ESP-16", "territorial-analysis", "consultative", 4, "Interface municipal", "Condicionante urbanística simulada recebida."),
      branch("BR-0519-JUR", "ESP-13", "conformity", "consultative", 4, "Revisão jurídica da condicionante", "Condicionante mantida com revisão humana."),
    ],
    stageSummaries: stageSummaries("ZEE e zoneamento consultados", "Score 55 e condicionante proposta", "Câmara de Uso do Solo"),
  },
  {
    id: "PROC-2026-0520",
    title: "Indício documental de sensibilidade hídrica",
    processType: "Captação e unidade de beneficiamento",
    applicant: "Empreendedor Simulado Iota Agro",
    municipality: "Ribeirão Preto, SP",
    sector: "Agroindústria",
    center: [-47.81, -21.177],
    polygon: processRing(-47.81, -21.177, 0.018),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Recarga e drenagem sem camada cartográfica",
    evidence: [attributeEvidence("recharge-indication", "Sensibilidade hídrica", "1 indício", "Referência documental a recarga e drenagem; cruzamento espacial ainda não demonstrado no mapa", "Declaração ambiental sintética")],
    conflict: conflict("Sensibilidade hídrica a verificar", "A referência documental exige avaliação da Câmara de Águas"),
    recommendation: recommendation(52, "Análise hídrica especializada", "Câmara de Águas e Recursos Hídricos", "2026-09-09T18:00:00.000Z"),
    arrivalTick: 17,
    branches: [
      branch("BR-0520-APP", "ESP-05", "territorial-analysis", "blocking", 4, "Análise hidrográfica", "Verificação cartográfica solicitada; interferência não confirmada no mapa."),
      branch("BR-0520-RSK", "ESP-12", "territorial-analysis", "consultative", 4, "Avaliação de risco ambiental", "Risco moderado registrado."),
    ],
    stageSummaries: stageSummaries("Recarga e drenagem aguardam conferência cartográfica", "Score 52 e análise hídrica", "Câmara de Águas e Recursos Hídricos"),
  },
  {
    id: "PROC-2026-0521",
    title: "Mudança recente de cobertura vegetal",
    processType: "Expansão de pátio agroindustrial",
    applicant: "Empreendedor Simulado Kappa Alimentos",
    municipality: "Presidente Prudente, SP",
    sector: "Agroindústria",
    center: [-50.375346, -21.80812],
    polygon: processRing(-50.375346, -21.80812, 0.018),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Imagem multitemporal simulada",
    evidence: [attributeEvidence("vegetation-change", "Mudança de cobertura", "6,4 ha", "Alteração recente identificada na série de imagens", "Imagens sintéticas de duas datas")],
    conflict: conflict("Alerta territorial", "Mudança recente exige verificação técnica e possível fiscalização"),
    recommendation: recommendation(64, "Análise aprofundada com fiscalização", "Câmara de Biodiversidade", "2026-09-07T18:00:00.000Z"),
    arrivalTick: 19,
    branches: [
      branch("BR-0521-IMG", "ESP-09", "territorial-analysis", "blocking", 5, "Análise multitemporal", "Mudança de 6,4 ha confirmada."),
      branch("BR-0521-BIO", "ESP-11", "territorial-analysis", "consultative", 4, "Avaliação de biodiversidade", "Impacto sobre fragmento indicado para revisão."),
      branch("BR-0521-FIS", "ESP-15", "territorial-analysis", "parallel", 5, "Preparação de fiscalização", "Ordem de vistoria simulada preparada."),
    ],
    stageSummaries: stageSummaries("Mudança de cobertura analisada", "Score 64 e fiscalização recomendada", "Câmara de Biodiversidade"),
  },
  {
    id: "PROC-2026-0522",
    title: "Indícios de manguezal e risco de inundação",
    processType: "Retroárea portuária",
    applicant: "Empreendedor Simulado Lambda Portos",
    municipality: "Santos, SP",
    sector: "Infraestrutura portuária",
    center: [-46.333, -23.96],
    polygon: processRing(-46.333, -23.96, 0.012),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Manguezal e inundação sem camada cartográfica",
    evidence: [attributeEvidence("mangrove-risk", "Receptores sensíveis", "2 indícios", "Declaração menciona manguezal e inundação; extensão e proximidade dependem de camada cartográfica", "Declaração ambiental sintética")],
    conflict: conflict("Sensibilidades a verificar", "Consultas sobre manguezal e inundação precisam ser consolidadas"),
    recommendation: recommendation(76, "Análise integrada prioritária", "Câmara de Avaliação Integrada", "2026-09-06T18:00:00.000Z"),
    arrivalTick: 21,
    branches: [
      branch("BR-0522-BIO", "ESP-11", "territorial-analysis", "blocking", 5, "Avaliação de manguezal", "Verificação cartográfica pendente."),
      branch("BR-0522-RSK", "ESP-12", "territorial-analysis", "blocking", 5, "Modelagem de inundação", "Exposição a inundação pendente de validação."),
      branch("BR-0522-APP", "ESP-05", "territorial-analysis", "consultative", 4, "Análise de APP costeira", "Faixa de proteção ainda não delimitada."),
    ],
    stageSummaries: stageSummaries("Sensibilidades costeiras aguardam conferência cartográfica", "Score 76 e prioridade elevada", "Câmara de Avaliação Integrada"),
  },
  {
    id: "PROC-2026-0523",
    title: "Fonte territorial desatualizada",
    processType: "Centro de distribuição",
    applicant: "Empreendedor Simulado Mu Comércio",
    municipality: "Sorocaba, SP",
    sector: "Comércio e logística",
    center: [-47.103311, -23.280709],
    polygon: processRing(-47.103311, -23.280709, 0.014),
    mapZoom: 14,
    focusLayer: "ucUs",
    focusLayerLabel: "APA Cabreúva, fonte em revisão",
    evidence: [
      spatialEvidence("uc-us-cabreuva", "UC de Uso Sustentável", "interseção", "O polígono exibido está sobre a APA Cabreúva; conclusão sujeita à conferência da fonte", "UC de Uso Sustentável, camada fornecida"),
      attributeEvidence("stale-source", "Vigência da fonte", "14 meses", "A atualização da fonte exige revisão antes da conclusão", "Catálogo territorial sintético"),
    ],
    conflict: conflict("Fonte insuficiente", "A conclusão aguarda substituição demonstrativa da camada"),
    recommendation: recommendation(41, "Revisão após atualização de fonte", "Câmara de Atividades Gerais", "2026-09-11T18:00:00.000Z"),
    arrivalTick: 23,
    branches: [
      branch("BR-0523-SRC", "ESP-04", "territorial-analysis", "blocking", 5, "Verificação de vigência da fonte", "Fonte substituta sintética selecionada."),
      branch("BR-0523-ADM", "ESP-17", "territorial-analysis", "consultative", 4, "Resolução administrativa da fonte", "Substituição registrada na trilha."),
    ],
    stageSummaries: stageSummaries("Fonte substituta consultada", "Score 41 após atualização", "Câmara de Atividades Gerais"),
  },
  {
    id: "PROC-2026-0524",
    title: "Empreendimento linear em vários municípios",
    processType: "Linha de transmissão regional",
    applicant: "Empreendedor Simulado Nu Energia",
    municipality: "Vale do Paraíba, SP",
    sector: "Energia",
    center: [-45.56, -23.19],
    polygon: processRing(-45.56, -23.19, 0.05),
    mapZoom: 12,
    focusLayer: "none",
    focusLayerLabel: "Traçado regional sintético",
    evidence: [attributeEvidence("multi-municipal", "Abrangência declarada", "4 municípios", "O traçado regional e as quatro jurisdições são informados pelo cenário; limites municipais não estão no mapa", "Memorial sintético do empreendimento")],
    conflict: conflict("Articulação interinstitucional", "O traçado depende de respostas federais e municipais"),
    recommendation: recommendation(69, "Análise integrada regional", "Câmara de Avaliação Integrada", "2026-09-07T18:00:00.000Z"),
    arrivalTick: 25,
    branches: [
      branch("BR-0524-ZEE", "ESP-10", "territorial-analysis", "blocking", 5, "Compatibilidade regional com ZEE", "Quatro segmentos classificados."),
      branch("BR-0524-FED", "ESP-14", "territorial-analysis", "consultative", 5, "Articulação federal", "Manifestação simulada vinculada ao processo."),
      branch("BR-0524-MUN", "ESP-16", "territorial-analysis", "consultative", 5, "Coordenação municipal", "Respostas de quatro municípios consolidadas."),
      branch("BR-0524-SLA", "ESP-18", "routing", "parallel", 4, "Balanceamento de capacidade", "Câmara e prazo ajustados ao portfólio."),
    ],
    stageSummaries: stageSummaries("Traçado regional analisado", "Score 69 e articulação necessária", "Câmara de Avaliação Integrada"),
  },
  {
    id: "PROC-2026-0525",
    title: "Interferência em UC de Uso Sustentável",
    processType: "Complexo de armazenagem",
    applicant: "Empreendedor Simulado Xi Armazéns",
    municipality: "Botucatu, SP",
    sector: "Armazenagem",
    center: [-48.422, -22.888],
    polygon: processRing(-48.422, -22.888, 0.018),
    mapZoom: 14,
    focusLayer: "ucUs",
    focusLayerLabel: "APA Cuesta Guarani",
    evidence: [spatialEvidence("uc-us-botucatu", "UC de Uso Sustentável", "interseção", "Polígono sintético intercepta a APA Cuesta Guarani; extensão sujeita a medição", "UC de Uso Sustentável, camada fornecida")],
    conflict: conflict("Interferência em APA", "A implantação exige avaliação técnica da UC de Uso Sustentável"),
    recommendation: recommendation(57, "Revisão técnica de biodiversidade", "Câmara de Biodiversidade", "2026-09-08T18:00:00.000Z"),
    arrivalTick: 27,
    branches: [
      branch("BR-0525-BIO", "ESP-11", "territorial-analysis", "blocking", 5, "Análise de biodiversidade na APA", "Interferência territorial identificada."),
      branch("BR-0525-IMG", "ESP-09", "territorial-analysis", "consultative", 4, "Validação por imagem", "Verificação da cobertura recomendada."),
      branch("BR-0525-UCUS", "ESP-07", "territorial-analysis", "consultative", 4, "Consulta à UC de Uso Sustentável", "Sobreposição com a APA Cuesta Guarani identificada."),
    ],
    stageSummaries: stageSummaries("APA Cuesta Guarani analisada", "Score 57 e revisão de biodiversidade", "Câmara de Biodiversidade"),
  },
  {
    id: "PROC-2026-0526",
    title: "Processo duplicado e protocolo relacionado",
    processType: "Regularização de atividade existente",
    applicant: "Empreendedor Simulado Ômicron Serviços",
    municipality: "Registro, SP",
    sector: "Serviços",
    center: [-47.843, -24.497],
    polygon: processRing(-47.843, -24.497, 0.014),
    mapZoom: 14,
    focusLayer: "none",
    focusLayerLabel: "Vínculos administrativos simulados",
    evidence: [attributeEvidence("duplicate-process", "Vínculo de protocolo", "1 duplicidade", "Geometria e requerente coincidem com processo anterior", "Cadastro administrativo sintético")],
    conflict: conflict("Duplicidade administrativa", "O protocolo deve ser vinculado ao processo anterior"),
    recommendation: recommendation(28, "Vinculação e checklist", "Câmara de Atividades Gerais", "2026-09-12T18:00:00.000Z"),
    arrivalTick: 29,
    branches: [
      branch("BR-0526-CAD", "ESP-02", "geometry", "blocking", 4, "Comparação cadastral", "Duplicidade confirmada com protocolo anterior."),
      branch("BR-0526-ADM", "ESP-17", "geometry", "consultative", 4, "Vinculação administrativa", "Processos vinculados na simulação."),
      branch("BR-0526-NOT", "ESP-20", "geometry", "operational", 5, "Aviso ao analista", "Notificação de vínculo preparada."),
    ],
    stageSummaries: stageSummaries("Duplicidade e vínculo conferidos", "Score 28 e checklist recomendado", "Câmara de Atividades Gerais"),
  },
] satisfies readonly OperationScenario[];

export const ALL_OPERATION_SCENARIOS = SCENARIO_CATALOG;
export const OPERATION_SCENARIOS = SCENARIO_CATALOG.slice(0, 12);

function processRing(longitude: number, latitude: number, size: number): readonly (readonly [number, number])[] {
  const width = size;
  const height = size * 0.72;
  return [
    [longitude - width * 0.54, latitude - height * 0.24],
    [longitude - width * 0.18, latitude - height * 0.48],
    [longitude + width * 0.44, latitude - height * 0.36],
    [longitude + width * 0.62, latitude + height * 0.02],
    [longitude + width * 0.26, latitude + height * 0.46],
    [longitude - width * 0.32, latitude + height * 0.38],
    [longitude - width * 0.58, latitude + height * 0.04],
    [longitude - width * 0.54, latitude - height * 0.24],
  ];
}

function stageSummaries(territorial: string, conformity: string, chamber: string): Readonly<Record<AgentStage, string>> {
  return {
    receiving: "Protocolo e documentos recebidos",
    geometry: "Geometria validada sem erro topológico",
    "territorial-analysis": territorial,
    conformity,
    routing: `Processo encaminhado à ${chamber}`,
    opinion: "Minuta preparada com evidências rastreáveis",
  };
}

function branch(
  id: string,
  specialistId: OperationScenario["branches"][number]["specialistId"],
  originStage: AgentStage,
  mode: OperationScenario["branches"][number]["mode"],
  durationTicks: number,
  title: string,
  result: string,
  trigger: string = title,
): OperationScenario["branches"][number] {
  return { id, specialistId, originStage, mode, durationTicks, title, result, trigger };
}

function spatialEvidence(
  id: string,
  title: string,
  measure: string,
  detail: string,
  source: string,
): OperationScenario["evidence"][number] {
  return {
    kind: "spatial-overlap",
    id,
    title,
    measure,
    detail,
    source,
    observedAt: "2026-09-02",
    provenance: "synthetic-data",
  };
}

function attributeEvidence(
  id: string,
  title: string,
  measure: string,
  detail: string,
  source: string,
): OperationScenario["evidence"][number] {
  return {
    kind: "attribute-divergence",
    id,
    title,
    measure,
    detail,
    source,
    observedAt: "2026-09-02",
    provenance: "synthetic-data",
  };
}

function conflict(summary: string, detail: string): NonNullable<OperationScenario["conflict"]> {
  return { title: "Conflito detectado", summary, detail };
}

function recommendation(
  score: number,
  route: string,
  chamber: string,
  dueAt: string,
): OperationScenario["recommendation"] {
  return { score, route, chamber, dueAt, provenance: "simulated-result" };
}
